netty:
    port: 55302
server:
    port: 55304
spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 606584188574-5g2mi8bvic6j96dit8o7m21f9ds6d82r.apps.googleusercontent.com
                        client-secret: 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
                        scope: openid,profile,email,https://www.googleapis.com/auth/youtube
    logging:
        level:
            com.springbootlearning: DEBUG
            org.springframework.sercurity: TRACE
            org.springframework.sercurity.oauth2: TRACE
            org.springframework.web: TRACE
            org.springframework.web.reactive: TRACE



